In [37]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import LabelEncoder

## 1. Làm sạch và tiền xử lý dữ liệu

### Đọc dữ liệu

In [38]:
df = pd.read_csv('/content/data.csv', delimiter=';')
df = df.set_index('ID')
df

   First Name Last Name   Age Gender Department   Salary Date of Joining
ID
1        John       Doe  25.0      M      Sales  50000.0      01/01/2020
2        Jane     Smith  30.0      F  Marketing  60000.0      06/01/2018
3         Bod   Johnson  45.0      M         HR  70000.0      09/01/2016
4       Alice  Williams  33.0      F         IT  80000.0      02/01/2017
5       James     Brown  27.0      M      Sales  55000.0      03/01/2019
6       Sarah       Lee   NaN      F  Marketing  65000.0      12/01/2018
7     Michael     Davis  39.0      M         HR      NaN      08/01/2015
8       Susan    Miller  42.0      F         IT  90000.0      11/01/2014
9       David    Wilson  28.0      M      Sales  60000.0      05/01/2020
10      Emily     Brown  35.0      F  Marketing  55000.0      04/01/2017
11       John       Doe  25.0      M      Sales  50000.0      01/01/2020
12       John       Doe  25.0      M      Sales  50000.0      01/01/2020

### Xử lý missing values

In [39]:
#2.KT giá trị missing
print(df.isnull().sum())
#Làm đầy các giá trị trống
df['Age'].fillna(df['Age'].mean(), inplace = True)
df['Salary'].fillna(df['Salary'].mean(), inplace = True)

First Name         0
Last Name          0
Age                1
Gender             0
Department         0
Salary             1
Date of Joining    0
dtype: int64

<ipython-input-39-aacbdf7cbbd9>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace = True)
<ipython-input-39-aacbdf7cbbd9>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace = True)

### Xử lý dữ liệu trùng lặp

In [40]:
#3.Kiểm tra giá trị giống nhau
print(df.duplicated().sum())
df = df.drop_duplicates()
df

2

,First Name,Last Name,Age,Gender,Department,Salary,Date of Joining
ID,,,,,,,
1,John,Doe,25.000000,M,Sales,50000.000000,01/01/2020
2,Jane,Smith,30.000000,F,Marketing,60000.000000,06/01/2018
3,Bod,Johnson,45.000000,M,HR,70000.000000,09/01/2016
4,Alice,Williams,33.000000,F,IT,80000.000000,02/01/2017
5,James,Brown,27.000000,M,Sales,55000.000000,03/01/2019
6,Sarah,Lee,32.181818,F,Marketing,65000.000000,12/01/2018
7,Michael,Davis,39.000000,M,HR,62272.727273,08/01/2015
8,Susan,Miller,42.000000,F,IT,90000.000000,11/01/2014
9,David,Wilson,28.000000,M,Sales,60000.000000,05/01/2020
10,Emily,Brown,35.000000,F,Marketing,55000.000000,04/01/2017

### Mã hóa dữ liệu

In [41]:
# Mã hoá dữ liệu catergories
df = pd.get_dummies(df, columns =['Gender','Department'])

### Xử lý dữ liệu Datetime

In [42]:
#Xử lí dữ liệu datetime
##Chuyển cột date thành một đối tượng datetime
df['Date of Joining'] = pd.to_datetime(df['Date of Joining'])
##extract month and day of week
df['month'] = df['Date of Joining'].dt.month
df['day_of_week'] = df['Date of Joining'].dt.day_name()
##Drop column 'Date'
df = df.drop('Date of Joining', axis = 1)
df

,First Name,Last Name,Age,Salary,Gender_F,Gender_M,Department_HR,Department_IT,Department_Marketing,Department_Sales,month,day_of_week
ID,,,,,,,,,,,,
1,John,Doe,25.000000,50000.000000,False,True,False,False,False,True,1,Wednesday
2,Jane,Smith,30.000000,60000.000000,True,False,False,False,True,False,6,Friday
3,Bod,Johnson,45.000000,70000.000000,False,True,True,False,False,False,9,Thursday
4,Alice,Williams,33.000000,80000.000000,True,False,False,True,False,False,2,Wednesday
5,James,Brown,27.000000,55000.000000,False,True,False,False,False,True,3,Friday
6,Sarah,Lee,32.181818,65000.000000,True,False,False,False,True,False,12,Saturday
7,Michael,Davis,39.000000,62272.727273,False,True,True,False,False,False,8,Saturday
8,Susan,Miller,42.000000,90000.000000,True,False,False,True,False,False,11,Saturday
9,David,Wilson,28.000000,60000.000000,False,True,False,False,False,True,5,Friday
10,Emily,Brown,35.000000,55000.000000,True,False,False,False,True,False,4,Saturday

### Xử lý các giá trị ngoại lai

In [43]:
#Xử lí ngoại lai và chuẩn hoá data
df1 = df.drop(['First Name','Last Name','day_of_week'],axis = 1)
array = df1.values
array

array([[25.0, 50000.0, False, True, False, False, False, True, 1],
       [30.0, 60000.0, True, False, False, False, True, False, 6],
       [45.0, 70000.0, False, True, True, False, False, False, 9],
       [33.0, 80000.0, True, False, False, True, False, False, 2],
       [27.0, 55000.0, False, True, False, False, False, True, 3],
       [32.18181818181818, 65000.0, True, False, False, False, True,
        False, 12],
       [39.0, 62272.72727272727, False, True, True, False, False, False,
        8],
       [42.0, 90000.0, True, False, False, True, False, False, 11],
       [28.0, 60000.0, False, True, False, False, False, True, 5],
       [35.0, 55000.0, True, False, False, False, True, False, 4]],
      dtype=object)

### Chuẩn hóa và scaling dữ liệu

In [44]:
#Loại bỏ outlier bằng RobustScaler() loại bỏ outliers
robust_scaler = preprocessing.RobustScaler()
robust_df = robust_scaler.fit_transform(array)
robust_df = pd.DataFrame(robust_df)
robust_df

          0         1    2    3    4    5         6         7         8
0 -0.799043 -0.890909 -0.5  0.5  0.0  0.0  0.000000  1.333333 -0.818182
1 -0.272727 -0.090909  0.5 -0.5  0.0  0.0  1.333333  0.000000  0.090909
2  1.306220  0.709091 -0.5  0.5  1.0  0.0  0.000000  0.000000  0.636364
3  0.043062  1.509091  0.5 -0.5  0.0  1.0  0.000000  0.000000 -0.636364
4 -0.588517 -0.490909 -0.5  0.5  0.0  0.0  0.000000  1.333333 -0.454545
5 -0.043062  0.309091  0.5 -0.5  0.0  0.0  1.333333  0.000000  1.181818
6  0.674641  0.090909 -0.5  0.5  1.0  0.0  0.000000  0.000000  0.454545
7  0.990431  2.309091  0.5 -0.5  0.0  1.0  0.000000  0.000000  1.000000
8 -0.483254 -0.090909 -0.5  0.5  0.0  0.0  0.000000  1.333333 -0.090909
9  0.253589 -0.490909  0.5 -0.5  0.0  0.0  1.333333  0.000000 -0.272727

In [45]:
#Chuẩn hoá bằng z-score
standard_scaler = preprocessing.StandardScaler()
standard = standard_scaler.fit_transform(array)
standard_df = pd.DataFrame(standard,index = df.index)
print('Chuan hoa du lieu: \n',standard_df)

Chuan hoa du lieu:
            0         1    2    3    4    5         6         7         8
ID
1  -1.369782 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508
2  -0.575077 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853
3   1.809037  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740
4  -0.098254  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977
5  -1.051900 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.863446
6  -0.228297  0.023415  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654  1.643333
7   0.855391 -0.210732 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.529209
8   1.332214  2.169757  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654  1.364802
9  -0.892959 -0.405854 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.306384
10  0.219627 -0.835122  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.584915

In [46]:
#Scale bằng minmax
mm_scaler = preprocessing.MinMaxScaler()
minmax = mm_scaler.fit_transform(array)
minmax_df = pd.DataFrame(minmax,index = df.index)
print('Scaling dữ liệu \n', minmax_df)

Scaling dữ liệu
            0         1    2    3    4    5    6    7         8
ID
1   0.000000  0.000000  0.0  1.0  0.0  0.0  0.0  1.0  0.000000
2   0.250000  0.250000  1.0  0.0  0.0  0.0  1.0  0.0  0.454545
3   1.000000  0.500000  0.0  1.0  1.0  0.0  0.0  0.0  0.727273
4   0.400000  0.750000  1.0  0.0  0.0  1.0  0.0  0.0  0.090909
5   0.100000  0.125000  0.0  1.0  0.0  0.0  0.0  1.0  0.181818
6   0.359091  0.375000  1.0  0.0  0.0  0.0  1.0  0.0  1.000000
7   0.700000  0.306818  0.0  1.0  1.0  0.0  0.0  0.0  0.636364
8   0.850000  1.000000  1.0  0.0  0.0  1.0  0.0  0.0  0.909091
9   0.150000  0.250000  0.0  1.0  0.0  0.0  0.0  1.0  0.363636
10  0.500000  0.125000  1.0  0.0  0.0  0.0  1.0  0.0  0.272727

### Rời rạc hóa dữ liệu

In [47]:
#Rời rạc hoá dữ liệu
##10 equi-width range với cột đầu tiên của standard_df
df2 = standard_df.copy()
df2['equi-width_column0'] = pd.cut(x = df2[0], bins = 10)
print('Rời rạc hoá cột 0 bằng 10 equi-width ranges: \n',df2)

Rời rạc hoá cột 0 bằng 10 equi-width ranges:
            0         1    2    3    4    5         6         7         8  \
ID
1  -1.369782 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508
2  -0.575077 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853
3   1.809037  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740
4  -0.098254  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977
5  -1.051900 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.863446
6  -0.228297  0.023415  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654  1.643333
7   0.855391 -0.210732 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.529209
8   1.332214  2.169757  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654  1.364802
9  -0.892959 -0.405854 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.306384
10  0.219627 -0.835122  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.584915

   equi-width_column0
ID
1    (-1.373, -1.052]
2    (-0.734, -0.416]
3      (1.491, 1.809]
4     (-0.0983, 0.22]
5    (-1.373, -1.052]
6   (-0.416, -0.0983]
7      (0.538, 0.855]
8      (1.173, 1.491]
9    (-1.052, -0.734]
10    (-0.0983, 0.22]

In [48]:
##Sử dụng hàm pd.qcut()
df3 = standard_df.copy()
df3['equi-depth_column0'] = pd.qcut(df3[0],q=10)
print('Rời rạc hoá cột 0 bằng 10 equi-width ranges: \n',df3)

Rời rạc hoá cột 0 bằng 10 equi-width ranges:
            0         1    2    3    4    5         6         7         8  \
ID
1  -1.369782 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508
2  -0.575077 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853
3   1.809037  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740
4  -0.098254  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977
5  -1.051900 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.863446
6  -0.228297  0.023415  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654  1.643333
7   0.855391 -0.210732 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.529209
8   1.332214  2.169757  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654  1.364802
9  -0.892959 -0.405854 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.306384
10  0.219627 -0.835122  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.584915

   equi-depth_column0
ID
1    (-1.371, -1.084]
2     (-0.67, -0.367]
3       (1.38, 1.809]
4    (-0.163, 0.0289]
5    (-1.084, -0.925]
6    (-0.367, -0.163]
7       (0.41, 0.951]
8       (0.951, 1.38]
9     (-0.925, -0.67]
10     (0.0289, 0.41]

## 2. Bài tập vận dụng

### Đọc dữ liệu

In [49]:
df = pd.read_csv('/content/arrhythmia.data', delimiter = ',', header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,1
448,37,0,190,85,100,137,361,201,73,86,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,10
449,36,0,166,68,108,176,365,194,116,-85,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,2
450,32,1,155,55,93,106,386,218,63,54,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,1
451,78,1,160,70,79,127,364,138,78,28,...,0.0,10.4,-1.8,0.0,0.0,0.5,1.6,21.3,32.8,1

### Xác định thông tin của dataframe, phát hiện các cột có kiểu object và thay đổi kiểu null cho '?'

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Columns: 280 entries, 0 to 279
dtypes: float64(120), int64(155), object(5)
memory usage: 988.9+ KB

In [51]:
# Xác định các cột có kiểu dữ liệu object
object_columns = df.select_dtypes(include=['object']).columns

# Hiển thị một số giá trị từ các cột này
df[object_columns].head()

   10   11  12  13  14
0  13   64  -2   ?  63
1  37  -17  31   ?  53
2  34   70  66  23  75
3  11   -5  20   ?  71
4  13   61   3   ?   ?

In [52]:
# Thay thế '?' bằng NaN
df.replace('?', np.nan, inplace=True)

### Mã hóa các cột có kiểu dữ liệu object

In [53]:
label_encoder = LabelEncoder()

# Mã hóa dữ liệu categorical
for col in df.select_dtypes(include=['object']).columns:
    df[col] = label_encoder.fit_transform(df[col])

### Kiểm tra missing values

In [54]:
# Kiểm tra số lượng giá trị missing
missing_values = df.isnull().sum().sum()
missing_values

np.int64(0)

### Kiểm tra dữ liệu trùng lặp

In [55]:
#3.Kiểm tra giá trị giống nhau
df.duplicated().sum()

np.int64(0)

### Xử lý các giá trị ngoại lai

In [56]:
#Loại bỏ outlier bằng RobustScaler() loại bỏ outliers
robust_scaler = preprocessing.RobustScaler()
robust_df = robust_scaler.fit_transform(df)
robust_df = pd.DataFrame(robust_df)
robust_df

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,1.272727,-1.0,2.6,0.60,0.357143,1.090909,0.117647,0.387097,1.304348,-0.899598,...,0.000000,0.043478,0.095238,0.0,0.0,1.333333,0.96875,0.361739,0.911983,1.4
1,0.409091,0.0,0.1,-0.20,-0.357143,0.515152,1.000000,-0.419355,-2.260870,-0.240964,...,0.000000,-0.065217,0.523810,0.0,0.0,-1.000000,0.46875,0.160000,0.462354,1.0
2,0.318182,-1.0,0.8,1.35,3.714286,0.181818,0.558824,0.741935,0.478261,0.899598,...,0.000000,0.152174,-0.619048,0.0,0.0,-0.666667,1.28125,-0.403478,0.895016,1.8
3,0.363636,-1.0,1.1,1.30,1.000000,1.363636,0.382353,0.548387,2.260870,-0.192771,...,0.000000,0.739130,-0.523810,0.0,0.0,-0.333333,0.78125,1.147826,1.429480,0.0
4,1.272727,-1.0,2.6,0.60,0.142857,0.727273,-0.205882,0.483871,0.521739,-0.899598,...,0.000000,0.934783,-1.190476,0.0,0.0,-2.000000,1.59375,0.507826,1.480382,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,0.272727,0.0,-0.4,0.10,-0.428571,1.272727,0.441176,-0.258065,1.130435,-1.236948,...,0.000000,-0.978261,-1.857143,0.0,0.0,0.666667,-0.46875,-1.565217,-1.204666,0.0
448,-0.454545,-1.0,2.6,0.85,1.000000,-0.606061,-0.176471,1.258065,-0.782609,0.738956,...,0.000000,1.478261,-0.238095,0.0,0.0,-0.333333,0.65625,1.384348,1.463415,1.8
449,-0.500000,-1.0,0.2,0.00,1.571429,0.575758,-0.058824,1.032258,1.086957,-2.008032,...,0.000000,1.630435,-13.095238,0.0,0.0,3.333333,-0.21875,-4.333913,-2.591729,0.2
450,-0.681818,0.0,-0.9,-0.65,0.500000,-1.545455,0.558824,1.806452,-1.217391,0.224900,...,-0.941176,0.695652,0.190476,0.0,0.0,0.000000,0.65625,0.480000,0.793213,0.0
451,1.409091,0.0,-0.4,0.10,-0.500000,-0.909091,-0.088235,-0.774194,-0.565217,-0.192771,...,0.000000,0.347826,-0.333333,0.0,0.0,0.000000,0.15625,0.222609,0.207847,0.0

In [57]:
#Chuẩn hoá bằng z-score
standard_scaler = preprocessing.StandardScaler()
standard = standard_scaler.fit_transform(robust_df)
standard_df = pd.DataFrame(standard,index = df.index)
print('Chuan hoa du lieu: \n',standard_df)

Chuan hoa du lieu:
           0         1         2         3         4         5         6    \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141
..        ...       ...       ...       ...       ...       ...       ...
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195

          7         8         9    ...       270       271        272  \
0    0.113809  1.201469 -1.094661  ...  0.508843 -0.013839   0.278621
1   -0.588564 -1.977064 -0.191203  ...  0.508843 -0.157972   0.728573
2    0.422853  0.464980  1.373324  ...  0.508843  0.130294  -0.471299
3    0.254284  2.054247 -0.125096  ...  0.508843  0.908612  -0.371310
4    0.198094  0.503742 -1.094661  ...  0.508843  1.168051  -1.071235
..        ...       ...       ...  ...       ...       ...        ...
447 -0.448089  1.046419 -1.557409  ...  0.508843 -1.368689  -1.771161
448  0.872372 -0.659136  1.152968  ...  0.508843  1.888716  -0.071342
449  0.675708  1.007656 -2.615116  ...  0.508843  2.090502 -13.569901
450  1.349985 -1.046762  0.447829  ... -0.220727  0.850959   0.378610
451 -0.897608 -0.465323 -0.125096  ...  0.508843  0.389733  -0.171331

          273  274       275       276       277       278       279
0   -0.079546  0.0  1.109553  1.177737  0.294603  1.078670  0.935771
1   -0.079546  0.0 -0.906889  0.616126  0.079613  0.504874  0.481455
2   -0.079546  0.0 -0.618826  1.528744 -0.520878  1.057018  1.390087
3   -0.079546  0.0 -0.330763  0.967133  1.132324  1.739077 -0.654336
4   -0.079546  0.0 -1.771079  1.879751  0.450286  1.804035  0.708613
..        ...  ...       ...       ...       ...       ...       ...
447 -0.079546  0.0  0.533427 -0.436895 -1.758926 -1.622502 -0.654336
448 -0.079546  0.0 -0.330763  0.826730  1.384382  1.782383  1.390087
449 -0.079546  0.0  2.837932 -0.156089 -4.709483 -3.392610 -0.427178
450 -0.079546  0.0 -0.042700  0.826730  0.420632  0.927101 -0.654336
451 -0.079546  0.0 -0.042700  0.265119  0.146334  0.180084 -0.654336

[452 rows x 280 columns]

In [58]:
#Scale bằng minmax scaling
df_new_minmax = pd.DataFrame(mm_scaler.fit_transform(robust_df), columns = df.columns)
df_new_minmax

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,0.903614,0.0,0.125926,0.435294,0.270677,0.368321,0.501805,0.241758,0.590244,0.457478,...,1.000000,0.381356,0.968531,0.0,0.0,0.53125,0.741667,0.507519,0.569579,0.466667
1,0.674699,1.0,0.088889,0.341176,0.195489,0.332061,0.610108,0.150183,0.190244,0.577713,...,1.000000,0.360169,1.000000,0.0,0.0,0.31250,0.675000,0.485714,0.500971,0.333333
2,0.650602,0.0,0.099259,0.523529,0.624060,0.311069,0.555957,0.282051,0.497561,0.785924,...,1.000000,0.402542,0.916084,0.0,0.0,0.34375,0.783333,0.424812,0.566990,0.600000
3,0.662651,0.0,0.103704,0.517647,0.338346,0.385496,0.534296,0.260073,0.697561,0.586510,...,1.000000,0.516949,0.923077,0.0,0.0,0.37500,0.716667,0.592481,0.648544,0.000000
4,0.903614,0.0,0.125926,0.435294,0.248120,0.345420,0.462094,0.252747,0.502439,0.457478,...,1.000000,0.555085,0.874126,0.0,0.0,0.21875,0.825000,0.523308,0.656311,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,0.638554,1.0,0.081481,0.376471,0.187970,0.379771,0.541516,0.168498,0.570732,0.395894,...,1.000000,0.182203,0.825175,0.0,0.0,0.46875,0.550000,0.299248,0.246602,0.000000
448,0.445783,0.0,0.125926,0.464706,0.338346,0.261450,0.465704,0.340659,0.356098,0.756598,...,1.000000,0.661017,0.944056,0.0,0.0,0.37500,0.700000,0.618045,0.653722,0.600000
449,0.433735,0.0,0.090370,0.364706,0.398496,0.335878,0.480144,0.315018,0.565854,0.255132,...,1.000000,0.690678,0.000000,0.0,0.0,0.71875,0.583333,0.000000,0.034951,0.066667
450,0.385542,1.0,0.074074,0.288235,0.285714,0.202290,0.555957,0.402930,0.307317,0.662757,...,0.902439,0.508475,0.975524,0.0,0.0,0.40625,0.700000,0.520301,0.551456,0.000000
451,0.939759,1.0,0.081481,0.376471,0.180451,0.242366,0.476534,0.109890,0.380488,0.586510,...,1.000000,0.440678,0.937063,0.0,0.0,0.40625,0.633333,0.492481,0.462136,0.000000

### Rời rạc hóa dữ liệu

In [59]:
#Rời rạc hoá dữ liệu
####10 equi-width range với cột đã chuẩn hoá dữ liệu
df2 = standard_df.copy()
df2['equi-width_column0'] = pd.cut(x = df2[0], bins = 10)
print('Rời rạc hoá cột 0 bằng 10 equi-width ranges: \n',df2)

Rời rạc hoá cột 0 bằng 10 equi-width ranges:
             0         1         2         3         4         5         6  \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141
..        ...       ...       ...       ...       ...       ...       ...
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195

            7         8         9  ...       271        272       273  274  \
0    0.113809  1.201469 -1.094661  ... -0.013839   0.278621 -0.079546  0.0
1   -0.588564 -1.977064 -0.191203  ... -0.157972   0.728573 -0.079546  0.0
2    0.422853  0.464980  1.373324  ...  0.130294  -0.471299 -0.079546  0.0
3    0.254284  2.054247 -0.125096  ...  0.908612  -0.371310 -0.079546  0.0
4    0.198094  0.503742 -1.094661  ...  1.168051  -1.071235 -0.079546  0.0
..        ...       ...       ...  ...       ...        ...       ...  ...
447 -0.448089  1.046419 -1.557409  ... -1.368689  -1.771161 -0.079546  0.0
448  0.872372 -0.659136  1.152968  ...  1.888716  -0.071342 -0.079546  0.0
449  0.675708  1.007656 -2.615116  ...  2.090502 -13.569901 -0.079546  0.0
450  1.349985 -1.046762  0.447829  ...  0.850959   0.378610 -0.079546  0.0
451 -0.897608 -0.465323 -0.125096  ...  0.389733  -0.171331 -0.079546  0.0

          275       276       277       278       279  equi-width_column0
0    1.109553  1.177737  0.294603  1.078670  0.935771      (1.716, 2.221]
1   -0.906889  0.616126  0.079613  0.504874  0.481455      (0.202, 0.707]
2   -0.618826  1.528744 -0.520878  1.057018  1.390087      (0.202, 0.707]
3   -0.330763  0.967133  1.132324  1.739077 -0.654336      (0.202, 0.707]
4   -1.771079  1.879751  0.450286  1.804035  0.708613      (1.716, 2.221]
..        ...       ...       ...       ...       ...                 ...
447  0.533427 -0.436895 -1.758926 -1.622502 -0.654336      (0.202, 0.707]
448 -0.330763  0.826730  1.384382  1.782383  1.390087    (-0.807, -0.302]
449  2.837932 -0.156089 -4.709483 -3.392610 -0.427178    (-0.807, -0.302]
450 -0.042700  0.826730  0.420632  0.927101 -0.654336    (-1.311, -0.807]
451 -0.042700  0.265119  0.146334  0.180084 -0.654336      (1.716, 2.221]

[452 rows x 281 columns]

In [60]:
####10 equi-depth range với cột đã chuẩn hoá dữ liệu
df3 = standard_df.copy()
df3['equi-depth_column0'] = pd.qcut(x = df3[0], q = 10)
print('Rời rạc hoá cột 0 bằng 10 equi-depth ranges: \n',df3)

Rời rạc hoá cột 0 bằng 10 equi-depth ranges:
             0         1         2         3         4         5         6  \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141
..        ...       ...       ...       ...       ...       ...       ...
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195

            7         8         9  ...       271        272       273  274  \
0    0.113809  1.201469 -1.094661  ... -0.013839   0.278621 -0.079546  0.0
1   -0.588564 -1.977064 -0.191203  ... -0.157972   0.728573 -0.079546  0.0
2    0.422853  0.464980  1.373324  ...  0.130294  -0.471299 -0.079546  0.0
3    0.254284  2.054247 -0.125096  ...  0.908612  -0.371310 -0.079546  0.0
4    0.198094  0.503742 -1.094661  ...  1.168051  -1.071235 -0.079546  0.0
..        ...       ...       ...  ...       ...        ...       ...  ...
447 -0.448089  1.046419 -1.557409  ... -1.368689  -1.771161 -0.079546  0.0
448  0.872372 -0.659136  1.152968  ...  1.888716  -0.071342 -0.079546  0.0
449  0.675708  1.007656 -2.615116  ...  2.090502 -13.569901 -0.079546  0.0
450  1.349985 -1.046762  0.447829  ...  0.850959   0.378610 -0.079546  0.0
451 -0.897608 -0.465323 -0.125096  ...  0.389733  -0.171331 -0.079546  0.0

          275       276       277       278       279  equi-depth_column0
0    1.109553  1.177737  0.294603  1.078670  0.935771      (1.248, 2.221]
1   -0.906889  0.616126  0.079613  0.504874  0.481455      (0.275, 0.579]
2   -0.618826  1.528744 -0.520878  1.057018  1.390087      (0.275, 0.579]
3   -0.330763  0.967133  1.132324  1.739077 -0.654336      (0.275, 0.579]
4   -1.771079  1.879751  0.450286  1.804035  0.708613      (1.248, 2.221]
..        ...       ...       ...       ...       ...                 ...
447  0.533427 -0.436895 -1.758926 -1.622502 -0.654336      (0.275, 0.579]
448 -0.330763  0.826730  1.384382  1.782383  1.390087    (-0.758, -0.576]
449  2.837932 -0.156089 -4.709483 -3.392610 -0.427178    (-0.758, -0.576]
450 -0.042700  0.826730  0.420632  0.927101 -0.654336    (-1.245, -0.758]
451 -0.042700  0.265119  0.146334  0.180084 -0.654336      (1.248, 2.221]

[452 rows x 281 columns]

## 3. Sử dụng mục 1 để làm sạch dữ liệu và tiền xử lý dữ liệu, và sử dụng PCA trong thư viện sklearn để làm mục 3.

### Đọc dữ liệu

In [61]:
#Đọc Musk Dataset
df3 = pd.read_csv('/content/clean2.data',delimiter = ',',header = None)
df3

,0,1,2,3,4,5,6,7,8,9,...,159,160,161,162,163,164,165,166,167,168
0,MUSK-211,211_1+1,46,-108,-60,-69,-117,49,38,-161,...,-308,52,-7,39,126,156,-50,-112,96,1.0
1,MUSK-211,211_1+10,41,-188,-145,22,-117,-6,57,-171,...,-59,-2,52,103,136,169,-61,-136,79,1.0
2,MUSK-211,211_1+11,46,-194,-145,28,-117,73,57,-168,...,-134,-154,57,143,142,165,-67,-145,39,1.0
3,MUSK-211,211_1+12,41,-188,-145,22,-117,-7,57,-170,...,-60,-4,52,104,136,168,-60,-135,80,1.0
4,MUSK-211,211_1+13,41,-188,-145,22,-117,-7,57,-170,...,-60,-4,52,104,137,168,-60,-135,80,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6593,NON-MUSK-jp13,jp13_2+5,51,-123,-23,-108,-117,134,-160,82,...,-66,164,-14,-29,107,171,-44,-115,118,0.0
6594,NON-MUSK-jp13,jp13_2+6,44,-104,-19,-105,-117,142,-165,68,...,-51,166,-9,150,129,158,-66,-144,-5,0.0
6595,NON-MUSK-jp13,jp13_2+7,44,-102,-19,-104,-117,72,-165,65,...,90,117,-8,150,130,159,-66,-144,-6,0.0
6596,NON-MUSK-jp13,jp13_2+8,51,-121,-23,-106,-117,63,-161,79,...,86,99,-14,-31,106,171,-44,-116,117,0.0
6597,NON-MUSK-jp13,jp13_2+9,51,-122,-23,-106,-117,190,-161,80,...,40,124,-14,-30,107,171,-44,-115,118,0.0

### Kiểm tra missing values

In [62]:
df3.isnull().sum().sum()

np.int64(0)

### Kiểm tra dữ liệu trùng lặp

In [63]:
df3.duplicated().sum()

np.int64(0)

### Xác định các dữ liệu kiểu object

In [64]:
# Xác định các cột có kiểu dữ liệu object
object_columns = df3.select_dtypes(include=['object']).columns

df3[object_columns].head()

          0         1
0  MUSK-211   211_1+1
1  MUSK-211  211_1+10
2  MUSK-211  211_1+11
3  MUSK-211  211_1+12
4  MUSK-211  211_1+13

Sau khi xác định được thì chỉ dữ liệu những cột có kiểu dữ liệu số, tức là loại 2 cột đầu

In [65]:
numeric_df = df3.iloc[:, 2:]

### Xử lý các giá trị ngoại lai

In [66]:
#Loại bỏ outlier
# Áp dụng Robust Scaling
df3_robust = pd.DataFrame(robust_scaler.fit_transform(numeric_df), columns=numeric_df.columns)

df3_robust.head()

,2,3,4,5,6,7,8,9,10,11,...,159,160,161,162,163,164,165,166,167,168
0,0.1250,0.418367,0.330508,-0.392857,0.0,0.156863,0.050926,-1.232877,0.163265,0.337469,...,-0.385417,0.712062,0.177215,-0.134731,0.327586,-0.714286,0.434783,0.644068,0.539062,1.0
1,-0.1875,-0.397959,-0.389831,0.419643,0.0,-0.382353,0.138889,-1.301370,0.005102,-0.704715,...,0.911458,0.501946,0.924051,0.248503,0.500000,-0.448980,-0.043478,0.237288,0.406250,1.0
2,0.1250,-0.459184,-0.389831,0.473214,0.0,0.392157,0.138889,-1.280822,0.005102,0.069479,...,0.520833,-0.089494,0.987342,0.488024,0.603448,-0.530612,-0.304348,0.084746,0.093750,1.0
3,-0.1875,-0.397959,-0.389831,0.419643,0.0,-0.392157,0.138889,-1.294521,0.005102,-0.694789,...,0.906250,0.494163,0.924051,0.254491,0.500000,-0.469388,0.000000,0.254237,0.414062,1.0
4,-0.1875,-0.397959,-0.389831,0.419643,0.0,-0.392157,0.138889,-1.294521,0.005102,-0.694789,...,0.906250,0.494163,0.924051,0.254491,0.517241,-0.469388,0.000000,0.254237,0.414062,1.0

In [67]:
#Chuẩn hoá bằng z score
df3_z_score = pd.DataFrame(standard_scaler.fit_transform(df3_robust),columns =numeric_df.columns)
df3_z_score

,2,3,4,5,6,7,8,9,10,11,...,159,160,161,162,163,164,165,166,167,168
0,-0.243124,0.122552,0.193471,-0.849986,-0.209163,0.380210,0.451914,-1.761086,0.720127,0.686645,...,-1.142753,0.999563,0.273558,-0.253997,0.191712,-0.768792,-0.045613,0.503332,0.576245,2.342586
1,-0.337030,-0.758442,-1.057429,0.281313,-0.209163,-0.302278,0.616692,-1.871747,0.433934,-0.770000,...,1.166837,0.577198,1.119768,0.380582,0.329019,-0.550386,-0.245376,0.187598,0.395603,2.342586
2,-0.243124,-0.824517,-1.057429,0.355904,-0.209163,0.678023,0.616692,-1.838549,0.433934,0.312079,...,0.471177,-0.611680,1.191480,0.777193,0.411403,-0.617588,-0.354338,0.069197,-0.029436,2.342586
3,-0.337030,-0.758442,-1.057429,0.281313,-0.209163,-0.314686,0.616692,-1.860681,0.433934,-0.756127,...,1.157562,0.561555,1.119768,0.390497,0.329019,-0.567187,-0.227216,0.200753,0.406229,2.342586
4,-0.337030,-0.758442,-1.057429,0.281313,-0.209163,-0.314686,0.616692,-1.860681,0.433934,-0.756127,...,1.157562,0.561555,1.119768,0.390497,0.342749,-0.567187,-0.227216,0.200753,0.406229,2.342586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6593,-0.149219,-0.042634,0.737980,-1.334828,-0.209163,1.434964,-1.265242,0.927988,-1.329385,0.228843,...,1.101909,1.875579,0.173160,-0.928237,-0.069172,-0.516785,0.063349,0.463865,0.810016,-0.426879
6594,-0.280686,0.166602,0.796846,-1.297533,-0.209163,1.534234,-1.308605,0.773062,-1.283225,0.173351,...,1.241041,1.891222,0.244873,0.846601,0.232904,-0.735191,-0.336177,0.082353,-0.496980,-0.426879
6595,-0.280686,0.188627,0.796846,-1.285101,-0.209163,0.665614,-1.308605,0.739864,-1.227833,0.450808,...,2.548881,1.507965,0.259216,0.846601,0.246634,-0.718391,-0.336177,0.082353,-0.507606,-0.426879
6596,-0.149219,-0.020609,0.737980,-1.309965,-0.209163,0.553934,-1.273915,0.894790,-1.273993,0.201097,...,2.511779,1.367177,0.173160,-0.948068,-0.082902,-0.516785,0.063349,0.450710,0.799390,-0.426879
6597,-0.149219,-0.031622,0.737980,-1.309965,-0.209163,2.129860,-1.273915,0.905856,-1.301689,-0.104105,...,2.085108,1.562716,0.173160,-0.938152,-0.069172,-0.516785,0.063349,0.463865,0.810016,-0.426879

In [68]:
#Chuẩn hoá dữ liệu bằng minmax scaling
df3_minmax = pd.DataFrame(mm_scaler.fit_transform(df3_robust), columns = numeric_df.columns)
df3_minmax

,2,3,4,5,6,7,8,9,10,11,...,159,160,161,162,163,164,165,166,167,168
0,0.238390,0.309524,0.431452,0.163636,0.002257,0.605744,0.534527,0.117431,0.604592,0.562863,...,0.047393,0.680905,0.393293,0.299435,0.459906,0.150362,0.409247,0.530201,0.676611,1.0
1,0.222910,0.037415,0.088710,0.494545,0.002257,0.462141,0.583120,0.099083,0.525510,0.359768,...,0.637441,0.545226,0.573171,0.419962,0.483491,0.173913,0.390411,0.489933,0.656325,1.0
2,0.238390,0.017007,0.088710,0.516364,0.002257,0.668407,0.583120,0.104587,0.525510,0.510638,...,0.459716,0.163317,0.588415,0.495292,0.497642,0.166667,0.380137,0.474832,0.608592,1.0
3,0.222910,0.037415,0.088710,0.494545,0.002257,0.459530,0.583120,0.100917,0.525510,0.361702,...,0.635071,0.540201,0.573171,0.421846,0.483491,0.172101,0.392123,0.491611,0.657518,1.0
4,0.222910,0.037415,0.088710,0.494545,0.002257,0.459530,0.583120,0.100917,0.525510,0.361702,...,0.635071,0.540201,0.573171,0.421846,0.485849,0.172101,0.392123,0.491611,0.657518,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6593,0.253870,0.258503,0.580645,0.021818,0.002257,0.827676,0.028133,0.563303,0.038265,0.499033,...,0.620853,0.962312,0.371951,0.171375,0.415094,0.177536,0.419521,0.525168,0.702864,0.0
6594,0.232198,0.323129,0.596774,0.032727,0.002257,0.848564,0.015345,0.537615,0.051020,0.491296,...,0.656398,0.967337,0.387195,0.508475,0.466981,0.153986,0.381849,0.476510,0.556086,0.0
6595,0.232198,0.329932,0.596774,0.036364,0.002257,0.665796,0.015345,0.532110,0.066327,0.529981,...,0.990521,0.844221,0.390244,0.508475,0.469340,0.155797,0.381849,0.476510,0.554893,0.0
6596,0.253870,0.265306,0.580645,0.029091,0.002257,0.642298,0.025575,0.557798,0.053571,0.495164,...,0.981043,0.798995,0.371951,0.167608,0.412736,0.177536,0.419521,0.523490,0.701671,0.0
6597,0.253870,0.261905,0.580645,0.029091,0.002257,0.973890,0.025575,0.559633,0.045918,0.452611,...,0.872038,0.861809,0.371951,0.169492,0.415094,0.177536,0.419521,0.525168,0.702864,0.0

### Rời rạc hóa dữ liệu

In [69]:
#Rời rạc hoá dữ liệu
####10 equi-width range với cột đã chuẩn hoá dữ liệu
df2 = standard_df.copy()
df2['equi-width_column0'] = pd.cut(x = df2[0], bins = 10)
print('Rời rạc hoá cột 0 bằng 10 equi-width ranges: \n',df2)

Rời rạc hoá cột 0 bằng 10 equi-width ranges:
             0         1         2         3         4         5         6  \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141
..        ...       ...       ...       ...       ...       ...       ...
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195

            7         8         9  ...       271        272       273  274  \
0    0.113809  1.201469 -1.094661  ... -0.013839   0.278621 -0.079546  0.0
1   -0.588564 -1.977064 -0.191203  ... -0.157972   0.728573 -0.079546  0.0
2    0.422853  0.464980  1.373324  ...  0.130294  -0.471299 -0.079546  0.0
3    0.254284  2.054247 -0.125096  ...  0.908612  -0.371310 -0.079546  0.0
4    0.198094  0.503742 -1.094661  ...  1.168051  -1.071235 -0.079546  0.0
..        ...       ...       ...  ...       ...        ...       ...  ...
447 -0.448089  1.046419 -1.557409  ... -1.368689  -1.771161 -0.079546  0.0
448  0.872372 -0.659136  1.152968  ...  1.888716  -0.071342 -0.079546  0.0
449  0.675708  1.007656 -2.615116  ...  2.090502 -13.569901 -0.079546  0.0
450  1.349985 -1.046762  0.447829  ...  0.850959   0.378610 -0.079546  0.0
451 -0.897608 -0.465323 -0.125096  ...  0.389733  -0.171331 -0.079546  0.0

          275       276       277       278       279  equi-width_column0
0    1.109553  1.177737  0.294603  1.078670  0.935771      (1.716, 2.221]
1   -0.906889  0.616126  0.079613  0.504874  0.481455      (0.202, 0.707]
2   -0.618826  1.528744 -0.520878  1.057018  1.390087      (0.202, 0.707]
3   -0.330763  0.967133  1.132324  1.739077 -0.654336      (0.202, 0.707]
4   -1.771079  1.879751  0.450286  1.804035  0.708613      (1.716, 2.221]
..        ...       ...       ...       ...       ...                 ...
447  0.533427 -0.436895 -1.758926 -1.622502 -0.654336      (0.202, 0.707]
448 -0.330763  0.826730  1.384382  1.782383  1.390087    (-0.807, -0.302]
449  2.837932 -0.156089 -4.709483 -3.392610 -0.427178    (-0.807, -0.302]
450 -0.042700  0.826730  0.420632  0.927101 -0.654336    (-1.311, -0.807]
451 -0.042700  0.265119  0.146334  0.180084 -0.654336      (1.716, 2.221]

[452 rows x 281 columns]

In [70]:
####10 equi-depth range với cột đã chuẩn hoá dữ liệu
df3 = standard_df.copy()
df3['equi-depth_column0'] = pd.qcut(x = df3[0], q = 10)
print('Rời rạc hoá cột 0 bằng 10 equi-depth ranges: \n',df3)

Rời rạc hoá cột 0 bằng 10 equi-depth ranges:
             0         1         2         3         4         5         6  \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141
..        ...       ...       ...       ...       ...       ...       ...
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195

            7         8         9  ...       271        272       273  274  \
0    0.113809  1.201469 -1.094661  ... -0.013839   0.278621 -0.079546  0.0
1   -0.588564 -1.977064 -0.191203  ... -0.157972   0.728573 -0.079546  0.0
2    0.422853  0.464980  1.373324  ...  0.130294  -0.471299 -0.079546  0.0
3    0.254284  2.054247 -0.125096  ...  0.908612  -0.371310 -0.079546  0.0
4    0.198094  0.503742 -1.094661  ...  1.168051  -1.071235 -0.079546  0.0
..        ...       ...       ...  ...       ...        ...       ...  ...
447 -0.448089  1.046419 -1.557409  ... -1.368689  -1.771161 -0.079546  0.0
448  0.872372 -0.659136  1.152968  ...  1.888716  -0.071342 -0.079546  0.0
449  0.675708  1.007656 -2.615116  ...  2.090502 -13.569901 -0.079546  0.0
450  1.349985 -1.046762  0.447829  ...  0.850959   0.378610 -0.079546  0.0
451 -0.897608 -0.465323 -0.125096  ...  0.389733  -0.171331 -0.079546  0.0

          275       276       277       278       279  equi-depth_column0
0    1.109553  1.177737  0.294603  1.078670  0.935771      (1.248, 2.221]
1   -0.906889  0.616126  0.079613  0.504874  0.481455      (0.275, 0.579]
2   -0.618826  1.528744 -0.520878  1.057018  1.390087      (0.275, 0.579]
3   -0.330763  0.967133  1.132324  1.739077 -0.654336      (0.275, 0.579]
4   -1.771079  1.879751  0.450286  1.804035  0.708613      (1.248, 2.221]
..        ...       ...       ...       ...       ...                 ...
447  0.533427 -0.436895 -1.758926 -1.622502 -0.654336      (0.275, 0.579]
448 -0.330763  0.826730  1.384382  1.782383  1.390087    (-0.758, -0.576]
449  2.837932 -0.156089 -4.709483 -3.392610 -0.427178    (-0.758, -0.576]
450 -0.042700  0.826730  0.420632  0.927101 -0.654336    (-1.245, -0.758]
451 -0.042700  0.265119  0.146334  0.180084 -0.654336      (1.248, 2.221]

[452 rows x 281 columns]

### PCA

In [78]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)


df_pca = pca.fit_transform(df3_z_score)

eigenvalues = pca.explained_variance_

eigenvectors = pca.components_

df_pca.shape
print('Các trị riêng \n ', eigenvalues )
print('\n')
print('Các vecto riêng \n', eigenvectors)

Các trị riêng
  [48.60114973 29.64298948]


Các vecto riêng
 [[-2.08123395e-03 -7.86374312e-02 -1.16377054e-01  9.08751118e-02
   4.47068884e-03 -4.20880916e-02  1.29198772e-01 -3.59805591e-02
   1.25101450e-01 -9.64702777e-02  9.91761915e-03  3.41432712e-02
  -2.41761996e-02 -2.37192076e-02 -1.27348773e-02 -5.99324369e-03
   1.18405831e-01 -1.04062521e-02  1.56293075e-02 -4.41893640e-02
   1.03470041e-01  1.31202036e-01  1.26642362e-01 -9.41769198e-02
  -1.19197275e-01  1.17027110e-01  8.46274145e-02  7.36183036e-02
   5.31155223e-02 -1.16265378e-01 -1.11129819e-03 -1.22315975e-02
   8.73558629e-02 -1.00662563e-01  1.09022540e-01 -1.67009492e-02
   3.09352821e-02  8.48896864e-02 -1.16869225e-01  7.99673034e-02
  -1.14081296e-01 -1.30190090e-02 -6.09332298e-02 -4.68700335e-03
  -9.94585439e-03  8.27270010e-03  2.67703861e-02  9.94568768e-02
  -2.58819336e-02 -8.82015989e-02  6.71233594e-02  1.30156871e-01
   1.30119158e-01  8.65852352e-03 -7.00369665e-02  7.24061992e-02
   1.23737527e-01 -3.29085370e-02  1.71652079e-02 -1.10504788e-01
   8.78248304e-02 -4.27972844e-02  1.59833466e-02 -1.11528293e-01
   9.47902296e-02 -8.09968932e-03 -6.62959755e-03 -3.89826521e-02
  -5.19572966e-02 -3.80928360e-02 -1.16524916e-01 -1.14332938e-01
   3.14702394e-03 -1.00474222e-02 -3.84686283e-02  4.58752514e-03
   1.23915411e-01 -2.28979321e-02  3.55538234e-02  6.84914930e-03
   1.21645308e-01  1.30770908e-01  9.57965365e-02 -2.58270451e-02
  -1.20982427e-01  1.26321464e-01 -4.42086163e-02  4.97648261e-02
   8.05216802e-02 -1.10199935e-01 -2.93240969e-02 -3.81487201e-03
   1.12376412e-01 -2.56463534e-02  3.43860124e-02 -2.34941754e-02
   3.13524617e-03  1.28084152e-01 -1.25349930e-01  1.21573572e-01
  -1.07397972e-01 -6.00821634e-04 -8.74135805e-03  5.58621147e-03
  -1.04405413e-02 -2.91070002e-02  4.26152920e-02  9.61247851e-02
  -3.62370414e-02 -8.87767146e-03 -9.58777736e-03  1.22489860e-01
   1.32101898e-01  1.33321783e-01 -1.17252160e-01 -6.53217989e-02
  -1.14365336e-01  1.19757595e-01  1.26463536e-01  8.56593814e-02
  -1.19765142e-01 -7.07598812e-02 -9.43211432e-02  3.99114519e-02
  -1.46029989e-02 -2.40428173e-02 -9.11832449e-02 -1.11012634e-01
  -6.69152347e-02  1.02105913e-01  2.35498405e-02  3.10881890e-03
   6.10181035e-02  6.15691774e-03 -3.58158108e-02 -7.13711875e-02
   1.06282864e-01 -6.60943515e-02  1.21851561e-01  7.38648928e-02
   8.96804415e-02  7.80792462e-02  1.26253678e-01  1.29352779e-01
   7.22307236e-03  9.19081009e-03  4.64514210e-03 -6.36197636e-02
  -6.50820961e-02  8.28463998e-02  1.02445014e-01  1.06190851e-01
   1.12329518e-01 -9.88540123e-02 -1.30529021e-02 -6.58697124e-02
  -4.66810471e-02 -5.21027352e-02 -1.00002259e-01 -4.99424431e-02
  -6.03233032e-03  2.76993969e-03  2.51525515e-02 -2.61620933e-04
  -1.31094625e-02  2.02730915e-03  9.41788959e-03]
 [-1.05508456e-01  2.38717955e-02  4.50554187e-02  8.23476987e-02
  -2.94616571e-02 -2.03089809e-02 -3.64329473e-02  1.48916754e-01
  -4.50035138e-02 -4.11352196e-02  1.69330199e-01  1.37441248e-01
   7.99093035e-02  1.68389388e-01  1.70970573e-01  5.38368449e-02
  -2.99119610e-02  9.74800311e-02  1.44730438e-01  1.10233062e-01
  -8.65674598e-03 -2.91835074e-02 -2.19538778e-02 -6.66513746e-02
  -7.10872798e-02 -6.18070082e-02 -2.05781551e-02  1.58859445e-02
   3.91703984e-02 -7.71728078e-02 -4.65754319e-02 -3.62731334e-02
   2.18343978e-02 -8.98742273e-02  6.92740906e-02 -2.42615126e-02
   5.65353532e-02 -5.51440343e-02  2.79964321e-02 -4.64408080e-02
   4.33654940e-02 -4.37956735e-02  1.58667606e-04  1.73055661e-01
   1.70608352e-01  1.53001622e-01  3.28855942e-02 -4.96262133e-02
   1.44520124e-01  1.74831949e-02  6.73439793e-02 -3.22497549e-02
  -4.03175133e-02  1.35233151e-01 -6.59462951e-02 -2.30333096e-02
  -3.76327342e-02  4.33816843e-02  1.33623100e-02 -7.77130063e-02
   5.80197926e-02 -3.40695825e-03 -5.85853652e-02 -6.96119103e-02
   8.12877987e-02 -8.81343051e-02 -1.57626547e-02  6.36309009e-04
   2.67587091e-02  7.25564390e-03  4.57769149e-02  1.44171690e-02
   1.51633899e-01  1.61517979e-01  1.28090061e-01  3.75512092e-02
  -4.59576615e-02  1.67797240e-01  1.40651530e-01  1.66355804e-01
  -4.00084294e-02 -3.33258773e-02  3.56166547e-02  2.09584200e-02
  -6.63155052e-02 -4.63385725e-02  5.08794566e-02  1.96101793e-04
   6.39230684e-02 -7.50726095e-02 -1.20443978e-02 -8.97098033e-02
   7.10185294e-02  5.54892848e-02 -5.60022835e-02  4.72567073e-02
   4.62927894e-02 -4.11698645e-02  4.34342786e-02 -4.33103682e-02
   3.86898688e-02 -1.02064717e-01  1.64228810e-01  1.72760581e-01
   1.72012779e-01  1.38300123e-01  2.21283978e-02 -4.68003686e-02
   1.56771609e-01  1.71817906e-01  1.65921217e-01 -1.01582998e-02
  -2.92129465e-02 -3.04125989e-02 -6.37209004e-02 -5.58755030e-02
  -7.34548074e-02 -5.48380972e-02 -3.89190257e-02  2.74782489e-03
  -7.26836158e-02 -7.12870957e-02 -7.59565137e-02  3.78711451e-02
   1.93890660e-03 -1.84473089e-02 -7.76183609e-02 -8.55765859e-02
  -3.93402992e-02  7.38398801e-02 -1.39396519e-02  5.68437005e-02
   1.92994281e-02  1.23556985e-01  1.55780882e-01  2.22771745e-02
  -4.39678019e-02  4.57887973e-02 -4.76865776e-02  5.39096437e-05
   2.86361838e-02 -5.34541616e-02 -4.40961436e-02 -4.16064787e-02
  -4.56465474e-02  7.78725131e-04  2.42238034e-02  3.57769754e-02
   5.00852674e-02 -3.40267339e-02  4.69558022e-02  8.25268084e-02
   8.43787392e-02 -1.09507284e-04 -4.42486880e-02 -5.40187697e-03
   2.80855690e-02 -1.20381959e-02 -4.00050538e-02 -1.73667046e-02
  -1.89989703e-02 -8.92752263e-02 -3.80810834e-03 -6.18294512e-02
  -8.33191515e-02  2.22472893e-02 -3.83774970e-02]]